# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tesseract_Tester' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tesseract_Tester
  pod 'TesseractOCRiOS', '4.0.0'
  target 'Tesseract_TesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tesseract_TesterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
